
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888