[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"